### ISSUE TITLE
Include known Solar System objects already in the MPC in the simulated detections

### ISSUE THREAD

**Issue by mschwamb** [lsst-sssc/lsst-simulation#15]
It would be good in the next iteration to include everything that's in the MPC in the simulated database or pick a random subset of simulation objects that match roughly the discovery numbers today and set discoverysubmissiondate to NULL to mimic having things that are being detected that are a  previous before-LSST discovery. I imagine especially early in the survey for comets and candidate ISOs, we'll want to know if this in a new object or something previously known and the discoverysubmissiondate is an efficient way to do that, so it would be good to test code using this.

**Comment by mjuric** [comment]
Yup, this is on the TODO list.

We're planning to have a hybrid catalog for a data exchange test with the MPC in Sep/Oct. The sim database should be updated in time for that.

**Comment by mschwamb** [comment]
Sorted with DP0.3 (whoot!)
