### ISSUE TITLE
Move the SSSC hub into the LSST science platform deployment

### ISSUE THREAD

**Issue by mjuric** [lsst-sssc/lsst-simulation#6]
Our long-term goal is to run the SSSC JupyterHub within the LSST Science Platform. @leannep suggested the time to do that may be now.

Things to understand/verify:
* [x] Learn about the status of the LSP
  * [x] Where is the documentation?
  * [x] Who is the contact person?
  * [x] What's the expected reliability/uptime of the LSP at the moment?
  * [x] Are backups being done?
  * [x] What kind of compute instances are available?
  * [x] Can we authenticate against github
  * [x] Is the VPN still required?
* [ ] Technical issues
  * [x] Does it support shared directories (so groups of people can collaborate)?
  * [x] Can we have a directory with common datasets (~2TB)
  * [x] Can we have an environment with the LSST stack + Solar System software?
    * [x] Can we delegate the management of that environment to some SSSC members?
    * [ ] Related: are the environments set up so that adding packages is possible w/o generating new Docker images/restarting servers?
  * [ ] Can we have a MySQL database for the datasets?
    * [ ] Can we have admin privileges delegated on the database?
    * [ ] Can logging be supported (to analyze slow queries)
    * [ ] What kind of instances are available for the database?
    * [ ] Is there DBA support?
    * [ ] Can we get a web-based GUI access to the database? (e.g., phpMyAdmin would be sufficient).
* [ ] How much support can we get for maintenance/administration?
* [ ] How much of administration can be delegated?

I've mentioned this to @ctslater; we'll find some time to discuss this in detail.

**Comment by mjuric** [comment]
A few useful links:
* Community category for discussing the LSP: https://community.lsst.org/c/support/lsp/39
* Documentation for accessing the platform: https://nb.lsst.io/

**Comment by mjuric** [comment]
More useful links (from StackClub):
* https://github.com/LSSTScienceCollaborations/StackClub
* https://github.com/LSSTScienceCollaborations/StackClub/blob/master/GettingStarted/GettingStarted.md

**Comment by mschwamb** [comment]
Checking on whether this is doable for this June's sprint? sounds like the system was there yet and better to use a jupyterhub

**Comment by gpdf** [comment]
Just to complete the arc of this story - this will be demonstrated in a Data Preview 0.3 on the RSP.  See the technote [RTN-050](https://rtn-050.lsst.io/) for more details.
