### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by mschwamb** [lsst-sssc/lsst-simulation#7]
A website or read the docs or PDF with details of what is available and not available in the databases would be helpful

**Comment by mjuric** [comment]
Good idea.

@eggls6 is writing the release notes for the sims, I proposed we place them into this repository. Maybe as a readme to begin with (not sure what you've done so far @eggls6), but to evolve into a RtD-generated website?

**Comment by mschwamb** [comment]
Sorted with DP0.3
