### ISSUE TITLE
Jupyter notebook widgets?

### ISSUE THREAD

**Issue by mkelley** [lsst-sssc/lsst-simulation#8]
I thought I'd try making a widget to plot an object's lightcurve, but...

![image](https://user-images.githubusercontent.com/1138643/85213651-14adf100-b32f-11ea-83e8-c9472e9b3d5b.png)

I just got a text representation.  Any ideas?  The ipywidgets FAQ: says

> Answer: A text representation of the widget is printed if the widget control is not available. It may mean the widget JavaScript is still loading. If the message persists in the Jupyter Notebook or JupyterLab, it likely means that the widgets JavaScript library is either not installed or not enabled. See the installation instructions above for setup instructions.

https://ipywidgets.readthedocs.io/en/latest/user_install.html

**Comment by mjuric** [comment]
Hi @mkelley -- looks like `widgetsnbextension` didn't come installed by default in our base environment; I think I fixed it now:

![image](https://user-images.githubusercontent.com/620059/85319488-70cf5d00-b476-11ea-87d6-6bcb9492bb07.png)

Try it out.

**Comment by mjuric** [comment]
Need to add `conda install -n base widgetsnbextension` to the Docker image to make this work for everyone.

**Comment by mjuric** [comment]
Done (on https://hub.docker.com/layers/astronomycommons/sssc-hub-notebook/latest/images/sha256-23a2c3c7d4aa1738daddc7e10a0e9396be004f3057a6813cb4fba086c00d8d7e?context=explore).
